config/routes.rb
# == Route Map
#
#       Prefix Verb   URI Pattern                  Controller#Action
#         root GET    /                            pages#home
#        clubs GET    /clubs(.:format)             clubs#index
#              POST   /clubs(.:format)             clubs#create
#     new_club GET    /clubs/new(.:format)         clubs#new
#    edit_club GET    /clubs/:id/edit(.:format)    clubs#edit
#         club GET    /clubs/:id(.:format)         clubs#show
#              PATCH  /clubs/:id(.:format)         clubs#update
#              PUT    /clubs/:id(.:format)         clubs#update
#              DELETE /clubs/:id(.:format)         clubs#destroy
#        users GET    /users(.:format)             users#index
#              POST   /users(.:format)             users#create
#     new_user GET    /users/new(.:format)         users#new
#    edit_user GET    /users/:id/edit(.:format)    users#edit
#         user GET    /users/:id(.:format)         users#show
#              PATCH  /users/:id(.:format)         users#update
#              PUT    /users/:id(.:format)         users#update
#              DELETE /users/:id(.:format)         users#destroy
#        posts GET    /posts(.:format)             posts#index
#              POST   /posts(.:format)             posts#create
#     new_post GET    /posts/new(.:format)         posts#new
#    edit_post GET    /posts/:id/edit(.:format)    posts#edit
#         post GET    /posts/:id(.:format)         posts#show
#              PATCH  /posts/:id(.:format)         posts#update
#              PUT    /posts/:id(.:format)         posts#update
#              DELETE /posts/:id(.:format)         posts#destroy
#     comments GET    /comments(.:format)          comments#index
#              POST   /comments(.:format)          comments#create
#  new_comment GET    /comments/new(.:format)      comments#new
# edit_comment GET    /comments/:id/edit(.:format) comments#edit
#      comment GET    /comments/:id(.:format)      comments#show
#              PATCH  /comments/:id(.:format)      comments#update
#              PUT    /comments/:id(.:format)      comments#update
#              DELETE /comments/:id(.:format)      comments#destroy
#        login GET    /login(.:format)             sessions#new
#              POST   /login(.:format)             sessions#create
#              DELETE /login(.:format)             sessions#destroy
# 

Rails.application.routes.draw do

  root :to => 'pages#home'

  resources :clubs
  resources :users
  resources :posts
  resources :comments

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/login' => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/club.rb
# == Schema Information
#
# Table name: clubs
#
#  id         :integer          not null, primary key
#  name       :text
#  manager    :text
#  homeground :text
#  position   :integer
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Club < ApplicationRecord
    has_many :users
    has_many :posts
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController

  before_action  :check_if_logged_in
  before_action :must_be_admin, :only => [:edit]

  def index
    @clubs = Club.all

  end

  def new
    @club = Club.new
  end

  def create
    club = Club.create club_params
    redirect_to club
  end

  def edit
    @club = Club.find params[:id]
  end

  def show
    @club = Club.find params[:id]
    
  end

  def update
    club = Club.find params[:id]
    club.update club_params
    redirect_to club
  end

  def destroy
    club = Club.find params[:id]
    club.destroy
    redirect_to clubs_path
  end

private
def club_params
  params.require(:club).permit(:name, :manager, :homeground, :image)
end

end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_form.html.erb
<%= form_for @club do |f| %>
<div class="form-group">
  <fieldset>
  <%= f.label :name %>
  <%= f.text_field :name %>
</fieldset>
</div>
<div class="form-group">
  <fieldset>
  <%= f.label :manager%>
  <%= f.text_field :manager%>
</fieldset>
</div>
<div class="form-group">
  <fieldset>
  <%= f.label :homeground%>
  <%= f.text_field :homeground%>
</fieldset>
</div>
<div class="form-group">
  <fieldset>
  <%= f.label :position%>
  <%= f.text_field :position%>
</fieldset>
</div>
<div class="form-group">
  <fieldset>
  <%= f.label :image%>
  <%= f.url_field :image %>
</fieldset>
</div>

<fieldset>
  <label></label>
  <%= f.submit %>
</fieldset>
<% end %>

app/views/clubs/edit.html.erb
<h1>Edit club</h1>
<%= render :partial => 'form' %>

app/views/clubs/index.html.erb
<div class="panel-heading"><h1>Clubs</h1></div>

<div class="row">
  <% @clubs.each do |club| %>
    <div class="col-sm-3 logobox" style="background-image: url(<%= club.image %>)">
      <a href="<%= club_path(club.id) %>" class="yo">
    </a>

    </div>
  <% end %>
</div>

app/views/clubs/new.html.erb
<h1>Add a new club</h1>
<%= render :partial => 'form' %>

app/views/clubs/show.html.erb
<div class="clubdetails">
  <div class ="row">
	  <div class ="col-md-4">
      <div class="badge">
        <%= image_tag(@club.image, :class => 'thumb') %>
      </div>
    </div>
      <div class ="col-md-8">
        <h1> <%= @club.name %> </h1>
        <div class ="col-md-6">
          <ul>
          <li>  <span class="colourname">Manager:</span> <%= @club.manager %></li>
            <li>  <span class="colourname">Homeground:</span> <%= @club.homeground %></li>
          </ul>
          <div class="controls">
              <span class="colourname"><%= link_to 'Edit Club', edit_club_path(@club) %></span>
              <%= button_to 'Delete club', @club, :method => 'delete', :data => { :confirm => 'You sure?'} %>
          </div>
        </div>
        <div class ="col-md-6">
          <div class="members">
            <h5>Members</h5>
            <% @club.users.each do |cu| %>
              <ul>
                <li><%= link_to "#{cu.username}", user_path(cu) %></li>
              </ul>
            <% end %>
          </div>
      </div>
  </div>
</div>

<div class="block_1"></div> <hr />

<h2>New post</h2>

<div class="messagebox">
  <%= form_for(Post.new)do |f| %>
    <div class="form-group">
      <fieldset>
      <%= f.label :message %>
      <%= f.text_field :message, :class => 'form-control' %>
      </fieldset>
    </div>
    <div class="form-group" id="choice">
      <fieldset>
      <%= f.label :club_id %>
      <%= f.select :club_id, Club.pluck(:name, :id), :include_blank => true %>
      </fieldset>
    </div>

    <div class="form-group" id="choice">
      <fieldset>
      <%= f.label :user_id %>
      <%= f.select :user_id, User.pluck(:username, :id), :include_blank => true %>
      </fieldset>
    </div>

    <div class="subbut">
      <%= f.submit "Add new post", :class => 'btn btn-primary btn-sm'%>
    </div>
  <% end %>
</div>


<h2>All <%= @club.name %> Posts</h2>

<% @club.posts.each do |post| %>

  <div class="posts panel panel-default">
    <ul>
      <div class="messagepostbox">
        <span class="colourname"><%= post.user.username %>: </span> <%= post.message %>
        <li><%= post.created_at.strftime '%B %d, %H:%M' %></li>
      </div>

  <%= form_for Comment.new do |f| %>
      <%= hidden_field_tag 'comment[post_id]', post.id %>
      <%= f.label :note %>
      <%= f.text_area :note %>
      <div class="subbut">
        <%= f.submit "Comment" %>
      </div>
      <% end %>
      <% post.comments.each do |comment| %>
        <div class="comment panel panel-default">
          <ul>
            <span class="colourname"><%= link_to "#{comment.user.username}", user_path(comment.user)%></span> <li><%= comment.note %></li>
            <div class="username"><%= "#{time_ago_in_words(post.created_at)} ago" %>
            </div>
          </ul>
        </div>
      <% end %>
      </ul>
    </div>
  <% end %>